language: objective-c
osx_image: xcode7


install:
- pod install --verbose

script:
- xcodebuild build -scheme IDZSwiftCommonCryptoCocoaPodsTest -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' -workspace IDZSwiftCommonCryptoCocoaPodsTest.xcworkspace
